/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_999038_4[] = { 0, 11, 22 };

// (before - mean) / scale
const float ei_classifier_anom_scale_999038_4[3] = { 989.9408088584292, 598.9195033605249, 950.0542575145078 };
const float ei_classifier_anom_mean_999038_4[3] = { 1322.2177778428313, 830.8868242892175, 3424.473828352372 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters_999038_4[32] = {
	{ ( float[3] ) { -1.094397783279419, -1.254620909690857, -0.6853923797607422 }, 0.0466799216206242 },
	{ ( float[3] ) { 1.3814035654067993, 0.9897634387016296, -0.678723156452179 }, 0.2710497580015956 },
	{ ( float[3] ) { 1.1343438625335693, 1.1163438558578491, -0.6725484728813171 }, 0.3604345352118205 },
	{ ( float[3] ) { 1.9144946336746216, 1.5308051109313965, -0.666253387928009 }, 0.24755701418140436 },
	{ ( float[3] ) { -0.264810174703598, 0.4340619742870331, 0.9682260751724243 }, 0.3250569872302385 },
	{ ( float[3] ) { -0.17651377618312836, -0.21059498190879822, 1.4095611572265625 }, 0.3435125563541925 },
	{ ( float[3] ) { -0.15919427573680878, 0.3870534896850586, 0.5945361256599426 }, 0.37643192345590326 },
	{ ( float[3] ) { -0.1702287793159485, 0.20084518194198608, 1.5001540184020996 }, 0.31864775846908155 },
	{ ( float[3] ) { 1.3341554403305054, 1.3779716491699219, -0.6700682044029236 }, 0.31774005012475115 },
	{ ( float[3] ) { 0.7977268099784851, 0.4855804443359375, -0.6796501278877258 }, 0.24872857523412784 },
	{ ( float[3] ) { -0.30924341082572937, 0.4323398172855377, 1.3252089023590088 }, 0.3590366157861876 },
	{ ( float[3] ) { -0.18957452476024628, -0.390415757894516, 0.9248260259628296 }, 0.40363990561750235 },
	{ ( float[3] ) { 0.9417283535003662, 0.8017515540122986, -0.6765413880348206 }, 0.3390543268664147 },
	{ ( float[3] ) { -0.06860919296741486, 0.20836368203163147, 1.8164222240447998 }, 0.33038999888151777 },
	{ ( float[3] ) { 1.6585026979446411, 1.243512511253357, -0.6732915639877319 }, 0.3999195055314759 },
	{ ( float[3] ) { 0.18858149647712708, 0.005752605851739645, 2.0019845962524414 }, 0.3781509809000737 },
	{ ( float[3] ) { 0.02562115713953972, 0.4972808361053467, 1.9915937185287476 }, 0.37575977050746406 },
	{ ( float[3] ) { 1.14860999584198, 0.7753080725669861, -0.6781268119812012 }, 0.24739958110052024 },
	{ ( float[3] ) { 1.5947442054748535, 1.7548809051513672, -0.6678321957588196 }, 0.32920206636812605 },
	{ ( float[3] ) { -0.21532367169857025, 0.7786906361579895, 1.0692991018295288 }, 0.3585241816483765 },
	{ ( float[3] ) { -0.06644030660390854, 0.2516060173511505, 1.2165135145187378 }, 0.33521420248167216 },
	{ ( float[3] ) { 0.512636661529541, 0.4377565383911133, -0.6740304231643677 }, 0.4196213999221667 },
	{ ( float[3] ) { -0.09767124056816101, 0.5671018958091736, 1.5989576578140259 }, 0.34058593259961273 },
	{ ( float[3] ) { -0.08251984417438507, -0.14458417892456055, 1.8406949043273926 }, 0.41755102814254 },
	{ ( float[3] ) { -0.29677313566207886, -0.31958428025245667, 0.19138039648532867 }, 0.41554316660369406 },
	{ ( float[3] ) { -0.24251078069210052, -0.013834789395332336, 1.210144281387329 }, 0.3103732452686991 },
	{ ( float[3] ) { 2.418268918991089, 1.6800841093063354, -0.6789559721946716 }, 0.2598423931263823 },
	{ ( float[3] ) { -0.00039897486567497253, 0.27637436985969543, 2.5242159366607666 }, 0.41384329540651976 },
	{ ( float[3] ) { -0.3757018446922302, 0.16860844194889069, 1.0360232591629028 }, 0.29397925876992204 },
	{ ( float[3] ) { -0.4056170582771301, -0.01750396192073822, 0.7468889355659485 }, 0.38594856175053727 },
	{ ( float[3] ) { 0.07030898332595825, 0.7516164183616638, 2.129415273666382 }, 0.2825188273289399 },
	{ ( float[3] ) { 0.20126938819885254, 0.9600880742073059, 1.7230108976364136 }, 0.7626308160183242 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
